/*
Generated by Yara-Rules
On 13-07-2019
*/
include "./Packers/Javascript_exploit_and_obfuscation.yar"
include "./Packers/JJencode.yar"
include "./Packers/packer_compiler_signatures.yar"
include "./Packers/packer.yar"
include "./Packers/peid.yar"
